### ISSUE TITLE
Get success rate over 90%

### ISSUE THREAD

**Issue by rjambrecic** [airtai/captn-backend#681]
**Tasks:**
- [x] in a case of timeout error, retry up to 3 times with exponential timeout (restart from scratch in case it doesn't work, up to 3 times)
- [x] In case of max numbers of messages reached (This usually means the team is stuck - infinity loop) - retry from scratch
- [x] Update benchmark report: "Success", "Success with retry", "Failed"

**Check the problems from the end2end benchmark 2024-05-11 are resolved:**
- [x] Incorrect use of the ask_client_for_permission + modification function (create_campaign / create_ad_group_with_ad_and_keywords)
- [x] web_surfer_navigator repeating empty messages (because openai BadRequest is raised)
- [x] repeated TimeoutError in the campaign_creation_team - start the team from scratch
